services:
  redis-cache:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./dev-data/redis:/data
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - kind

  postgres-db:
    image: postgres:17.3-alpine3.20
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./env/postgres.env
    volumes:
      - ./dev-data/postgres:/var/lib/postgresql/data
    networks:
      - kind

  zookeeper:
    image: bitnami/zookeeper
    restart: always
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    volumes:
      - ./dev-data/zookeeper:/bitnami/zookeeper
    networks:
      - kind

  kafka-broker:
    image: bitnami/kafka:3.6.0
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-broker:9092"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    volumes:
      - ./dev-data/kafka:/bitnami/kafka
    networks:
      - kind

networks:
  kind:
    driver: bridge
