apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: triaina-backend
build:
  artifacts:
    - image: ghcr.io/ossamatammam/connection-test
      context: ./connection-test
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    gitCommit: {}
  local:
    push: true

manifests:
  rawYaml:
    - k8s/*.yaml
    - k8s/api-gateway/*.yaml
    - k8s/connection-test/*.yaml

deploy:
  helm:
    releases:
      - name: kong
        remoteChart: ingress
        repo: https://charts.konghq.com
        namespace: kong
        createNamespace: true
        valuesFiles:
          ## Config for the gateway
          - k8s/api-gateway/config/kong-values.yaml
        wait: true
    hooks:
      before:
        - host:
            command:
              [
                "kubectl",
                "apply",
                "-f",
                "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml",
              ]
