apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: triaina-backend
build:
  artifacts:
    ## connection testing
    - image: ghcr.io/ossamatammam/connection-test
      context: ./connection-test
      docker:
        dockerfile: Dockerfile
  local:
    push: true
manifests:
  rawYaml:
    ## For AWS settings and secrets
    - k8s/*.yaml
    ## Microservices
    - k8s/connection-test/*.yaml
