apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: triaina-backend
build:
  insecureRegistries:
    - localhost:5000
  artifacts:
    - image: localhost:5000/triaina-backend # skaffold lives on the machine
      context: ./services/triaina
      docker:
        dockerfile: Dockerfile.dev
  tagPolicy:
    customTemplate:
      template: "latest"
  local:
    push: false

manifests:
  rawYaml:
    - k8s/*.yaml
    - k8s/configmaps/*.yaml
    - k8s/secrets/*.yaml
    - k8s/api-gateway/*.yaml
    - k8s/triaina/*.yaml
deploy:
  helm:
    releases:
      - name: kong
        namespace: kong
        createNamespace: true
        repo: https://charts.konghq.com
        remoteChart: ingress
        valuesFiles:
          - ./k8s/api-gateway/config/kong-values.yaml
        wait: true
portForward:
  - resourceType: Service
    resourceName: kong-gateway-proxy
    namespace: kong
    port: 80
    localPort: 32069
