apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: triaina-backend
build:
  artifacts:
    - image: localhost:5001/triaina-backend # skaffold lives on the machine
      context: ./services/triaina
      docker:
        dockerfile: Dockerfile.dev
  tagPolicy:
    customTemplate:
      template: "latest"
  local:
    push: true

manifests:
  rawYaml:
    - k8s/*.yaml
    - k8s/configmaps/*.yaml
    - k8s/secrets/*.yaml
    - k8s/api-gateway/*.yaml
    - k8s/triaina/*.yaml

# deploy:
#   # helm:
#   #   releases:
#   #     - name: kong
#   #       # chartPath: ./k8s/.charts/ingress
#   #       remoteChart: ingress
#   #       repo: https://charts.konghq.com
#   #       namespace: kong
#   #       createNamespace: true
#   #       valuesFiles:
#   #         ## Config for the gateway
#   #         - k8s/api-gateway/config/kong-values.yaml
#   #       wait: true
#   #   hooks:
#   #     before:
#   #       - host:
#   #           command:
#   #             [
#   #               "kubectl",
#   #               "apply",
#   #               "-f",
#   #               "https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.2.0/standard-install.yaml",
#   #             ]
#   kubectl: {}
#   logs:
#     prefix: auto
portForward:
  - resourceType: Service
    resourceName: kong-gateway-proxy
    namespace: kong
    port: 80
    localPort: 32069
