apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: triaina-backend
build:
  artifacts:
    ## connection testing
    - image: ghcr.io/ossamatammam/connection-test
      context: ./connection-test
      docker:
        dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml ## For AWS settings and secrets
      ## Microservices
      - k8s/connection-test/*.yaml
