apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: triaina-backend
build:
  artifacts:
    ## user-service
    - image: user-service
      context: ./user-service
      docker:
        dockerfile: Dockerfile
  local:
    push: false # Don't push to a container registry, use local images (may change)
deploy:
  kubectl:
    manifests:
      - k8s/user-service/*.yaml
