#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: triaina
  host: <%= ENV.fetch("RDS_HOST", "localhost.localhost.cloud") %> # Default to localhost for development
  port: <%= ENV.fetch("RDS_PORT", "4512") %>
  username: <%= ENV.fetch("DB_USERNAME") %>
  password: <%= ENV.fetch("DB_PASSWORD") %>

production:
  primary: &primary_production
    <<: *default
    database: auth_service_production
    username: auth_service
    password: <%= ENV["AUTH_SERVICE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: auth_service_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: auth_service_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: auth_service_production_cable
    migrations_paths: db/cable_migrate
