gateway:
  admin:
    http:
      enabled: true
  ## Expose cluster to outside world on port 32001
  proxy:
    ## Will be switched to LoadBalancer eventually (when we get to using AWS not Localstack)
    type: NodePort
    http:
      enabled: true
      nodePort: 32069 # This port is exposed to the outside of the cluster
    tls:
      enabled: false
