gateway:
  proxy:
    type: NodePort
    http:
      enabled: true
      nodePort: 32060 # This port is exposed to the outside of the cluster
    https:
      enabled: true
    tls:
      enabled: true
