gateway:
  proxy:
    type: NodePort
    http:
      enabled: true
      nodePort: 32060 # This port is exposed to the outside of the cluster
    https:
      enabled: true
    tls:
      enabled: true
config:
  websocket: true
  connect_timeout: 60000  # milliseconds
  read_timeout: 60000     # milliseconds
  send_timeout: 60000     # milliseconds