default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: "user_service,public"

development:
  <<: *default
  database: triaina
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

production:
  primary: &primary_production
    <<: *default
    database: auth_service_production
    username: auth_service
    password: <%= ENV["AUTH_SERVICE_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: auth_service_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: auth_service_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: auth_service_production_cable
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: triaina_test
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
