source "https://rubygems.org"

gem "bcrypt", "~> 3.1", ">= 3.1.12"
gem "karafka", "~> 2.4"
gem "oj_serializers"
gem "pagy", "~> 9.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "pundit", "~> 2.5"
gem "rails", "~> 8.0.1"
gem "redis", "~> 5.2.0"
gem "sorbet", "~> 0.5.11708"
gem "jwt", "~> 2.10", ">= 2.10.1"

gem "solid_cable"
gem "solid_cache"
gem "solid_queue"

gem "bootsnap", require: false

gem "thruster", require: false

gem "aws-sdk-elasticache"
gem "aws-sdk-kafka"
gem "aws-sdk-rds"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

group :development, :test do
  gem "brakeman", require: false
  gem "byebug"
  gem "database_cleaner"
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "rspec-rails"
  gem "rubocop-rails-omakase", require: false
  gem "ruby-lsp", "~> 0.23.11"
  gem "shoulda-matchers", "~> 5.0"
end
