source "https://rubygems.org"

gem "bcrypt", "~> 3.1", ">= 3.1.12"
gem "karafka", "~> 2.4"
gem "oj_serializers"
gem "pagy", "~> 9.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "pundit", "~> 2.5"
gem "rails", "~> 8.0.1"
gem "redis", "~> 5.2.0"
gem "sorbet", "~> 0.5.11708"
gem "jwt", "~> 2.10", ">= 2.10.1"
gem "rswag-api"
gem "rswag-ui"

gem "solid_cable"
gem "solid_cache"
gem "solid_queue"

gem "bootsnap", require: false

gem "thruster", require: false

gem "aws-sdk-elasticache"
gem "aws-sdk-kafka"
gem "aws-sdk-rds"
gem "aws-sdk-s3"

# For the virgin windows users (Jinzou - Omar)
# gem "tzinfo-data", platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem "brakeman", require: false
  gem "byebug"
  gem "database_cleaner"
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "dotenv-rails"
  gem "factory_bot_rails"
  gem "faker"
  gem "rubocop-rails-omakase", require: false
  gem "ruby-lsp", "~> 0.23.11"
  gem "shoulda-matchers", "~> 5.0"
  gem "rspec-rails"
  gem "rswag-specs"
end
