---
openapi: 3.0.1
info:
  title: Triaina API
  version: v1
paths:
  "/api/v1/auth/signup":
    post:
      summary: User Signup
      tags:
      - Authentication
      parameters: []
      responses:
        '201':
          description: user created
        '422':
          description: validation failed
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                username:
                  type: string
                  example: johndoe
                  minLength: 4
                email:
                  type: string
                  format: email
                  example: johndoe@email.com
                password:
                  type: string
                  example: SecurePass123!
                password_confirmation:
                  type: string
                  example: SecurePass123!
              required:
              - name
              - username
              - email
              - password
              - password_confirmation
  "/api/v1/auth/login":
    post:
      summary: User Login
      tags:
      - Authentication
      parameters: []
      responses:
        '200':
          description: user logged in
        '401':
          description: invalid credentials
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: johndoe@email.com
                password:
                  type: string
                  example: SecurePass123!
              required:
              - email
              - password
  "/api/v1/course_sections":
    post:
      summary: Create a new course section
      tags:
      - Course Sections
      security:
      - cookie_auth: []
      parameters: []
      responses:
        '201':
          description: section created
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: New Section
                description:
                  type: string
                  example: New section description
                course_id:
                  type: integer
                  example: 1
              required:
              - title
              - course_id
  "/api/v1/course_sections/{id}":
    parameters:
    - name: id
      in: path
      description: Course Section ID
      required: true
      schema:
        type: string
    get:
      summary: Get a specific course section
      tags:
      - Course Sections
      security:
      - cookie_auth: []
      responses:
        '200':
          description: section found
        '401':
          description: unauthorized
    put:
      summary: Update a course section
      tags:
      - Course Sections
      security:
      - cookie_auth: []
      parameters: []
      responses:
        '200':
          description: section updated
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Updated Section Title
                description:
                  type: string
                  example: Updated section description
              required: []
    delete:
      summary: Delete a course section
      tags:
      - Course Sections
      security:
      - cookie_auth: []
      responses:
        '204':
          description: section deleted
        '401':
          description: unauthorized
  "/api/v1/courses":
    get:
      summary: List all courses
      tags:
      - Courses
      security:
      - cookie_auth: []
      responses:
        '200':
          description: courses found
        '401':
          description: unauthorized
    post:
      summary: Create a new course
      tags:
      - Courses
      security:
      - cookie_auth: []
      parameters: []
      responses:
        '201':
          description: course created
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: New Course
                description:
                  type: string
                  example: New course description
                start_date:
                  type: string
                  format: date_time
                  example: '2025-05-04T00:00:00.000Z'
                end_date:
                  type: string
                  format: date_time
                  nullable: true
              required:
              - name
              - description
              - start_date
  "/api/v1/courses/{id}":
    parameters:
    - name: id
      in: path
      description: Course ID
      required: true
      schema:
        type: string
    get:
      summary: Get a specific course
      tags:
      - Courses
      security:
      - cookie_auth: []
      responses:
        '200':
          description: course found
        '401':
          description: unauthorized
    put:
      summary: Update a course
      tags:
      - Courses
      security:
      - cookie_auth: []
      parameters: []
      responses:
        '200':
          description: course updated
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Updated Course Name
                description:
                  type: string
                  example: Updated course description
                start_date:
                  type: string
                  format: date_time
                  example: '2025-05-04T00:00:00.000Z'
                end_date:
                  type: string
                  format: date_time
                  nullable: true
              required: []
    delete:
      summary: Delete a course
      tags:
      - Courses
      security:
      - cookie_auth: []
      responses:
        '204':
          description: course deleted
        '401':
          description: unauthorized
  "/api/v1/section_units":
    post:
      summary: Create a new section unit
      tags:
      - Section Units
      security:
      - cookie_auth: []
      parameters: []
      responses:
        '201':
          description: unit created
        '401':
          description: unauthorized
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: string
        required: true
  "/api/v1/section_units/{id}":
    parameters:
    - name: id
      in: path
      description: Section Unit ID
      required: true
      schema:
        type: string
    get:
      summary: Get a specific section unit
      tags:
      - Section Units
      security:
      - cookie_auth: []
      responses:
        '200':
          description: unit found
        '401':
          description: unauthorized
    put:
      summary: Update a section unit
      tags:
      - Section Units
      security:
      - cookie_auth: []
      parameters: []
      responses:
        '200':
          description: unit updated
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Updated Unit Title
                description:
                  type: string
                  example: Updated unit description
              required: []
    delete:
      summary: Delete a section unit
      tags:
      - Section Units
      security:
      - cookie_auth: []
      responses:
        '204':
          description: unit deleted
        '401':
          description: unauthorized
  "/api/v1/users/{id}/courses":
    get:
      summary: List all courses for a user
      tags:
      - User Courses
      description: List of courses for a user
      security:
      - cookie_auth: []
      parameters:
      - name: id
        in: path
        required: true
        description: User ID
        schema:
          type: integer
      responses:
        '200':
          description: List of courses
          content:
            application/json:
              schema:
                "$ref": "#/components/x-responses/User/Course/List"
        '401':
          description: Unauthorized
          content:
            application/json:
              examples:
                example_0:
                  value:
                  - success: 'false'
                    message: Unauthorized Action!
                  - success: 'false'
                    message: Missing token in the sent header!
                  - success: 'false'
                    message: Invalid token, Authorization failed!
                  - success: 'false'
                    message: Token expired, Authorization failed!
              schema:
                "$ref": "#/components/schemas/error"
        '404':
          description: User not found
          content:
            application/json:
              examples:
                example_0:
                  value:
                    success: 'false'
                    message: Can not find record with id 1
              schema:
                "$ref": "#/components/schemas/error"
  "/api/v1/users/me":
    get:
      summary: Fetch the current user
      tags:
      - Users
      security:
      - cookie_auth: []
      responses:
        '200':
          description: user found
        '401':
          description: unauthorized
    patch:
      summary: Update the current user
      tags:
      - Users
      security:
      - cookie_auth: []
      parameters: []
      responses:
        '200':
          description: user updated
        '401':
          description: unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: johndoe@email.com
                username:
                  type: string
                  minLength: 4
                  example: johndoe
              required: []
    delete:
      summary: Delete the current user
      tags:
      - Users
      security:
      - cookie_auth: []
      responses:
        '204':
          description: user deleted
        '401':
          description: unauthorized
servers:
- url: http://localhost:3000
  description: Local dev server (HTTP)
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: triaina.com
components:
  securitySchemes:
    jwtCookie:
      type: apiKey
      in: cookie
      name: jwt
    refreshCookie:
      type: apiKey
      in: cookie
      name: refresh_token
  parameters:
    id_param:
      name: id
      in: path
      description: The id to fetch with
      required: true
      schema:
        type: number
        example: 1
    locale_param:
      name: Accept-Language
      in: header
      type: string
      description: "A localiztion param and it only accepts **ar** or **en**. \n\n
        \            > Please note: in case of passing this param in any protected
        endpoint\n             it automatically overrides the locale of the current
        user"
      required: false
      schema:
        type: string
        example: ar
        default: en
    page_param:
      name: page
      in: query
      description: The current page for paginated items, send it with value = -1 if
        no pagination needed
      schema:
        type: number
        example: 3
    items_param:
      name: items
      in: query
      description: The number of items per page
      schema:
        type: number
        example: 10
  schemas:
    error:
      type: object
      required:
      - success
      - message
      properties:
        success:
          type: boolean
          description: response status failure
        message:
          type: string
          description: validation error message
    Unit:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Unit 1
        description:
          type: string
          example: Unit 1 description
        order_index:
          type: integer
          example: 1
        section_id:
          type: integer
          example: 1
        content_url:
          type: string
          example: https://example.com/unit1.mp4
      required:
      - id
      - title
      - description
      - order_index
      - section_id
      - content_url
    Section:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Section 1
        description:
          type: string
          example: Section 1 description
        order_index:
          type: integer
          example: 1
        course_id:
          type: integer
          example: 1
        units:
          type: array
          items:
            "$ref": "#/components/schemas/Unit"
      required:
      - id
      - title
      - description
      - order_index
      - course_id
      - units
    Course:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Course 1
        description:
          type: string
          example: Course 1 description
        join_code:
          type: string
          example: '123456'
        start_date:
          type: string
          example: '2025-01-01'
        end_date:
          type: string
          example: '2025-01-01'
        sections:
          type: array
          items:
            "$ref": "#/components/schemas/Section"
      required:
      - id
      - name
      - description
      - join_code
      - start_date
      - end_date
      - sections
  x-responses:
    User:
      Course:
        List:
          type: object
          required:
          - success
          - data
          properties:
            success:
              type: boolean
              example: true
            message:
              type: string
              description: response message
            courses:
              type: array
              items:
                "$ref": "#/components/schemas/Course"
