default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  schema_search_path: "triaina,public"

development:
  <<: *default
  database: triaina
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "triaina") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USERNAME") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

  cache:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "triaina") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USERNAME") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "triaina") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USERNAME") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "triaina") %>
    host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5432) %>
    username: <%= ENV.fetch("POSTGRES_USERNAME") %>
    password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: triaina_test
  host: <%= ENV.fetch("POSTGRES_HOST", "localhost") %>
  port: <%= ENV.fetch("POSTGRES_PORT", "5432") %>
  username: <%= ENV.fetch("POSTGRES_USERNAME") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
