source "https://rubygems.org"

gem "rails", "~> 8.0.1"
gem "sorbet", "~> 0.5.11708"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "redis", "~> 5.2.0"
gem "rdkafka", "~> 0.19.0"

gem "solid_cache"
gem "solid_queue"
gem "solid_cable"

gem "bootsnap", require: false

gem "kamal", require: false


gem "thruster", require: false

gem "aws-sdk-rds"
gem "aws-sdk-elasticache"
gem "aws-sdk-kafka"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
# gem "rack-cors"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem "dotenv-rails"
  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false
end
