name: "Triaina Backend Push CI/CD"

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v6
        with:
          context: ./services/triaina-backend
          file: ./services/triaina-backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ secrets.GHCR_USERNAME }}/triaina-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
