name: "Ruby on Rails CI/CD"
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: rails
      POSTGRES_PASSWORD: password
      JWT_SECRET: secret
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: triaina_test
          POSTGRES_USER: ${{ env.POSTGRES_USERNAME }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
    
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build Docker image with cache
        uses: docker/build-push-action@v6
        with:
          context: ./services/triaina
          file: ./services/triaina/Dockerfile.dev
          tags: triaina-backend:latest
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            RAILS_ENV=${{ env.RAILS_ENV }}

      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e RAILS_ENV=${{ env.RAILS_ENV }} \
            -e POSTGRES_HOST=${{ env.POSTGRES_HOST }} \
            -e POSTGRES_PORT=${{ env.POSTGRES_PORT }} \
            -e POSTGRES_USERNAME=${{ env.POSTGRES_USERNAME }} \
            -e POSTGRES_PASSWORD=${{ env.POSTGRES_PASSWORD }} \
            -e JWT_SECRET=${{ env.JWT_SECRET }} \
            triaina-backend:latest \
            rails db:prepare && bundle exec rspec spec/tests --exclude-pattern "spec/tests/requests/api/v1/user/course_spec.rb"
      - name: Push Docker image (only if tests passed)
        if: success()
        uses: docker/build-push-action@v6
        with:
          context: ./services/triaina
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: ghcr.io/${{secrets.GHCR_USERNAME}}/${{secrets.GHCR_REPO_NAME}}:latest

