name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: triaina_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: rails
      POSTGRES_PASSWORD: password
      JWT_SECRET: secret
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t triaina-backend -f Dockerfile.dev .
        working-directory: services/triaina
      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e RAILS_ENV=test \
            -e POSTGRES_HOST=localhost \
            -e POSTGRES_PORT=5432 \
            -e POSTGRES_USERNAME=rails \
            -e POSTGRES_PASSWORD=password \
            triaina-backend \
            bundle exec rspec
        working-directory: services/triaina



  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@78c01b705fd9d5ad960d432d3a0cfa341d50e410 # v1.179.1
  #       with:
  #         bundler-cache: true
  #     - name: Generate binstubs
  #       run: bundle binstubs bundler-audit brakeman rubocop
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
