name: "Ruby on Rails CI/CD"
on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: triaina_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: rails
      POSTGRES_PASSWORD: password
      JWT_SECRET: secret
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build \
            -f Dockerfile.dev \
            --network=host \
            --build-arg RAILS_ENV=test \
            -t triaina-backend:latest \
            ./services/triaina

      - name: Run tests
        run: |
          docker run --rm \
            -e RAILS_ENV=test \
            -e POSTGRES_HOST=localhost \
            -e POSTGRES_PORT=5432 \
            -e POSTGRES_USERNAME=rails \
            -e POSTGRES_PASSWORD=password \
            -e JWT_SECRET=secret \
            triaina-backend:latest \
            bundle exec rspec spec/tests --exclude-pattern "spec/tests/models/section_unit_spec.rb"
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     token: # Use PAT (Personal Access Token) from GitHub Secrets
          # This token should have write access to the GitHub Container Registry
      # - name: Push Docker image (only if tests passed)
      #   if: success()
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./services/triaina
      #     file: Dockerfile
      #     push: true
      #     tags: ghcr.io/OssamaTammam/triaina-backend:latest

